# Generated by Django 2.1 on 2021-07-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('sub_category_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('download_link', models.URLField()),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
    ]
