# Generated by Django 2.1 on 2021-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curl_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover',
            field=models.ImageField(default='index.jpeg', upload_to=''),
        ),
    ]
