# Generated by Django 2.1 on 2021-07-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curl_video', '0002_video_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='temp.mp4', upload_to=''),
        ),
    ]
