# Generated by Django 2.1 on 2021-07-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curl_video', '0003_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(default='index.jpeg', upload_to='media/%y'),
        ),
    ]
